import {
    ArrowRight,
    Bookmark,
    BookOpen,
    Check,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    CircleCheck,
    Clock,
    Copy,
    Crown,
    Database,
    Download,
    Ellipsis,
    ExternalLink,
    Eye,
    Flame,
    Funnel,
    Gauge,
    Info,
    LayoutGrid,
    List,
    LoaderCircle,
    LogOut,
    Minus,
    OctagonX,
    Pencil,
    Plus,
    PlugZap,
    Search,
    Settings,
    Share2,
    Shield,
    Skull,
    SlidersHorizontal,
    Star,
    Sword,
    Swords,
    Terminal,
    Trash2,
    TriangleAlert,
    User,
    X,
    Zap,
} from '@lucide/vue';
import type { LucideIcon } from '@lucide/vue';

/**
 * The Lucide vocabulary the design system uses, keyed by the kebab-case name the
 * prototype and the design system readme refer to. Add a glyph here before using
 * it — icons are never imported directly into a screen.
 */
export const bybIcons = {
    'arrow-right': ArrowRight,
    'book-open': BookOpen,
    bookmark: Bookmark,
    check: Check,
    'chevron-down': ChevronDown,
    'chevron-left': ChevronLeft,
    'chevron-right': ChevronRight,
    'circle-check': CircleCheck,
    clock: Clock,
    copy: Copy,
    crown: Crown,
    database: Database,
    download: Download,
    ellipsis: Ellipsis,
    'external-link': ExternalLink,
    eye: Eye,
    flame: Flame,
    funnel: Funnel,
    gauge: Gauge,
    info: Info,
    'layout-grid': LayoutGrid,
    list: List,
    'loader-circle': LoaderCircle,
    'log-out': LogOut,
    minus: Minus,
    'octagon-x': OctagonX,
    pencil: Pencil,
    'plug-zap': PlugZap,
    plus: Plus,
    search: Search,
    settings: Settings,
    'share-2': Share2,
    shield: Shield,
    skull: Skull,
    'sliders-horizontal': SlidersHorizontal,
    star: Star,
    sword: Sword,
    swords: Swords,
    terminal: Terminal,
    'trash-2': Trash2,
    'triangle-alert': TriangleAlert,
    user: User,
    x: X,
    zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof bybIcons;

/** Icons are 11px inside labels, 13px inline with text, 16px default, 20px in panel headers. */
export type IconSize = 11 | 13 | 16 | 20;
